// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuP5T_lAHYd4MYBcUXJc9cntwlNPL5Pak',
    appId: '1:1070100510061:web:f8576334ab04d6865a5664',
    messagingSenderId: '1070100510061',
    projectId: 'medishare-e6b5c',
    authDomain: 'medishare-e6b5c.firebaseapp.com',
    storageBucket: 'medishare-e6b5c.firebasestorage.app',
    measurementId: 'G-M0NW5DC03W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJc7fFvYH92IDKGLL25xQuGRIiuS7yiDg',
    appId: '1:1070100510061:android:bcbeb691c11bcd475a5664',
    messagingSenderId: '1070100510061',
    projectId: 'medishare-e6b5c',
    storageBucket: 'medishare-e6b5c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVlBUWKtLjNtLfCf8G5We1m9fMtc3gXLI',
    appId: '1:1070100510061:ios:340a11e2c5d3a34e5a5664',
    messagingSenderId: '1070100510061',
    projectId: 'medishare-e6b5c',
    storageBucket: 'medishare-e6b5c.firebasestorage.app',
    iosBundleId: 'com.example.medishare',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVlBUWKtLjNtLfCf8G5We1m9fMtc3gXLI',
    appId: '1:1070100510061:ios:340a11e2c5d3a34e5a5664',
    messagingSenderId: '1070100510061',
    projectId: 'medishare-e6b5c',
    storageBucket: 'medishare-e6b5c.firebasestorage.app',
    iosBundleId: 'com.example.medishare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuP5T_lAHYd4MYBcUXJc9cntwlNPL5Pak',
    appId: '1:1070100510061:web:04427c9cc27201675a5664',
    messagingSenderId: '1070100510061',
    projectId: 'medishare-e6b5c',
    authDomain: 'medishare-e6b5c.firebaseapp.com',
    storageBucket: 'medishare-e6b5c.firebasestorage.app',
    measurementId: 'G-PWCPC26VS2',
  );
}
